# Generated by Django 5.0.6 on 2024-05-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
